backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"

publish_mode: editorial_workflow
media_folder: "data/uploads"
public_folder: "/uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "data/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
