backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"

publish_mode: editorial_workflow
media_folder: "data/uploads"
public_folder: "/uploads"

collections:
  - name: "books"
    label: "Books"
    file: "data/books.json"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "publisher", label: "Publisher", widget: "string", required: false }
      - { name: "description", label: "Description", widget: "text", required: false }
