backend:
  name: git-gateway
  branch: main
  identity_url: https://chaegbarlibrary.netlify.app/.netlify/identity
  gateway_url: https://chaegbarlibrary.netlify.app/.netlify/git

media_folder: "data/uploads"
public_folder: "/data/uploads"
