backend:
  name: github
  repo: simwooram123/chaegbarlibrary
  branch: main

media_folder: "data/uploads"
public_folder: "/uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "data/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }

  - name: "comments"
    label: "Comments"
    folder: "data/comments"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string", default: "Anonymous" }
      - { label: "Message", name: "message", widget: "text" }
